#What is the goal of your workflow
# Goal: Whenever someone changes the python code.
#the linter will chekc if the syntac, format, indentation (linting) is correct or not

name: Auto Linter

on:
  push:
    paths: "*.py"
    

jobs:
  code-linting:
    runs-on: ubuntu-latest
    # this step will automatically clone the code of the current brach into the runner
    steps:
      # this step will automatically clone the code of current branch into the runner
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
      # this step will intsll python
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      # this step will install the linting tool ( rull is a python linter)
      - name: Install Linter
        run: pip install ruff
        # this step willl run the linter
      - name: check the file for linting
        run: ruff check .
  
